# Generated by Django 4.2.7 on 2023-12-03 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("bookId", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("edition", models.CharField(max_length=50)),
                ("numberOfCopies", models.IntegerField()),
                ("bookType", models.CharField(max_length=50)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Librarian",
            fields=[
                ("librarianId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transactionId", models.AutoField(primary_key=True, serialize=False)),
                ("issue_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("is_returned", models.BooleanField(default=False)),
                (
                    "bookId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LibManagementApp.book",
                    ),
                ),
                (
                    "librarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LibManagementApp.librarian",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("memberId", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_number", models.CharField(max_length=15)),
                ("books", models.ManyToManyField(to="LibManagementApp.book")),
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="librarian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="LibManagementApp.librarian",
            ),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("billId", models.AutoField(primary_key=True, serialize=False)),
                ("billDate", models.DateField()),
                ("amount", models.IntegerField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LibManagementApp.member",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LibManagementApp.transaction",
                    ),
                ),
            ],
        ),
    ]
