# Generated by Django 4.2.7 on 2023-11-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibManagementApp", "0002_librarian_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="bookId",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
