# Generated by Django 4.2.7 on 2023-11-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LibManagementApp", "0003_transaction_bookid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="memberID",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
