# Generated by Django 4.2.7 on 2023-11-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LibManagementApp", "0006_alter_member_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="user",),
    ]
